import { WorkshopSettings, FieldConfig } from '../types';

export const DEFAULT_WORKSHOP_SETTINGS: WorkshopSettings = {
  workshop_name: 'OSINT Masterclass: Open Source Threat Intelligence 2026',
  description: 'Master practical Open Source Intelligence (OSINT) techniques. Learn digital footprinting, geolocation verification, SOCMINT investigations, metadata analysis, and threat actor tracking using industry-standard tools.',
  date: '2026-10-15',
  time: '10:00 AM - 04:00 PM EST',
  venue: 'Cyber Tech Auditorium & Online Stream',
  organizer: 'Department of Cybersecurity & OSINT Research Group',
  registration_fee: 'Free',
  registration_deadline: '2026-10-14T23:59',
  max_participants: 150,
  contact_info: 'osint-workshop@cybersec.edu | +1 (555) 019-2831',
  workshop_banner: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
  registration_open: true,

  toggle_workshop_name: true,
  toggle_description: true,
  toggle_date: true,
  toggle_time: true,
  toggle_venue: true,
  toggle_organizer: true,
  toggle_registration_fee: true,
  toggle_registration_deadline: true,
  toggle_max_participants: true,
  toggle_workshop_banner: true,
  toggle_contact_info: true,
};

export const DEFAULT_FIELD_CONFIGS: FieldConfig[] = [
  {
    field_name: 'full_name',
    label: 'Full Name',
    placeholder: 'e.g. Alex Mercer',
    enabled: true,
    required: true,
    order_index: 1,
    field_type: 'text',
  },
  {
    field_name: 'email',
    label: 'Email Address',
    placeholder: 'e.g. alex.m@cybersec.org',
    enabled: true,
    required: true,
    order_index: 2,
    field_type: 'email',
  },
  {
    field_name: 'phone',
    label: 'Phone Number',
    placeholder: 'e.g. +1 (555) 019-2834',
    enabled: true,
    required: false,
    order_index: 3,
    field_type: 'tel',
  },
  {
    field_name: 'college',
    label: 'College / Institution',
    placeholder: 'e.g. Institute of Cyber Technology',
    enabled: true,
    required: true,
    order_index: 4,
    field_type: 'text',
  },
  {
    field_name: 'department',
    label: 'Department / Major',
    placeholder: 'e.g. Cybersecurity / Computer Science',
    enabled: true,
    required: false,
    order_index: 5,
    field_type: 'text',
  },
  {
    field_name: 'year_of_study',
    label: 'Year of Study',
    placeholder: 'Select Year of Study',
    enabled: true,
    required: false,
    order_index: 6,
    field_type: 'select',
    options: [
      '1st Year (Freshman)',
      '2nd Year (Sophomore)',
      '3rd Year (Junior)',
      '4th Year (Senior)',
      'Postgraduate / Masters',
      'Faculty / Professional',
    ],
  },
  {
    field_name: 'technical_experience',
    label: 'Technical Experience Level',
    placeholder: 'Select your OSINT / Security experience level',
    enabled: true,
    required: false,
    order_index: 7,
    field_type: 'select',
    options: [
      'Beginner (No prior OSINT experience)',
      'Intermediate (Basic search techniques)',
      'Advanced (Used Maltego, Shodan, Recon-ng)',
      'Professional / Researcher',
    ],
  },
  {
    field_name: 'reason',
    label: 'Reason for Attending',
    placeholder: 'What do you hope to learn from this workshop? (Optional)',
    enabled: true,
    required: false,
    order_index: 8,
    field_type: 'textarea',
  },
];
